const DATABASE_FILE = 'database.json';
const DATABASE_FOLDER_NAME = 'database';
const PATH_TO_DATABASE_FOLDER = __dirname + '\\' + DATABASE_FOLDER_NAME;
const PATH_TO_DATABASE_FILE = __dirname + '\\' + DATABASE_FILE;

exports.DATABASE_FILE = DATABASE_FILE;
exports.PATH_TO_DATABASE_FILE = PATH_TO_DATABASE_FILE;
exports.PATH_TO_DATABASE_FOLDER = PATH_TO_DATABASE_FOLDER;
